### ISSUE TITLE
3. Warehouse Default to Postgres is disappearing/not visible

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#106]
**Describe the bug**
The warehouse screen is showing postgres for a new users and then this disappears after I click somewhere and come back. 

**To Reproduce**
1. Go to https://ddpui.projecttech4dev.org/
2. Signup/Login with a user that hasn't done anything on the platform
3. Click on 'warehouse' The default postgres screen will show (if not, then step 6 will happen, which is also not desireable)
4. Click on connections
5. Click on 'warehouse' again.
6. You will see the screen changes to 'add warehouse'

**Expected behavior**
The warehouse screen should just show add warehouse and 

**Screenshots**
<img width="1470" alt="Screenshot 2023-06-15 at 8 21 37 AM" src="https://github.com/DevDataPlatform/webapp/assets/119285990/22eacea9-d529-48e3-b5f3-8b5520f6bb64">

@mdshamoon @fatchat

**Comment by fatchat** [comment]
@nairabhishek73 "not there to begin with" is the correct behaviour, if that's not happening we will fix it

why do you want a default?

**Comment by nairabhishek73** [comment]
Vinod explained that its supposed to default to Postgres.
www.glific.org

Glific product video <https://youtu.be/r6pI3YnINws> | Use cases
<https://glific.org/tag/case-study/>

LinkedIn <https://www.linkedin.com/showcase/glific/?viewAsMember=true> | Join
NGO community <https://discord.gg/cHnTF9x> | WhatsApp us
<https://api.whatsapp.com/send?phone=917302307943&text=Hi%20Glific%20team>Chintu
Gudiya Foundation <https://chintugudiya.org/>

Project Tech4Dev <https://chintugudiya.org/tag/tech4dev/>

**Comment by fatchat** [comment]
also add "your warehouse or ours"
