### ISSUE TITLE
4. Update the Transform Section of the DDP UI

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#107]
**Describe the task**

1. Add the run option
2. Add 3 clickable options 
 - Run
 - Other actions(clean, deps, test, docs-generate)- 
 - options/edit 3 dots
3. Keep one logs box for all DBT transform actions

**Expected behaviour**
All formatting should match that of Figma. With icons font characteristica, colour palette, etc.
All changes should be made as listed above.

**References**
[DDP UI](https://ddpui.projecttech4dev.org/pipeline/transform) 
[Figma](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=742-3039&viewport=301%2C2975%2C0.66&scaling=min-zoom)
[UI feedback working doc](https://docs.google.com/document/d/14WTXtiNGYG3Y7CRkhrD_tdKELZ3coEuyyJ0iXT6Eamw/edit?usp=sharing)

@mdshamoon

**Comment by nairabhishek73** [comment]
3 dots are not working. Keeping this comment here as I don't see another issue created.

For a new login adding their first transformation, it should say "Connect to DBT repository", not "Connect Repo"

**Comment by fatchat** [comment]
Linked to C4GT Community issue https://github.com/DevDataPlatform/webapp/issues/162 for the remaining tasks

**Comment by fatchat** [comment]
Edit DBT repo url + target schema is pending
