### ISSUE TITLE
5. Update the Orchestrate Section of the DDP UI

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#108]
**Describe the task**
1. For new flow>new connection you need to be able to do multi-select
2. For scheduling on new flow it says ‘select source type’
3. No option to edit- to be added, only enabling change schedules and make active or inactive and move on.
4. Add scheduled, show frequency
5. For time add ‘by x time everyday/week’
6. Show inactive/active in one column (this is our Orchestration State)
7. Show Passing/Failing in one column (This is our Last Flow Status) (passing=what was previously 'running')

**Expected behaviour**
All formatting should match that of Figma. With icons font characteristica, colour palette, etc.
All changes should be made as listed above.

**References**
[DDP UI](https://ddpui.projecttech4dev.org/pipeline/orchestrate) 
[Figma](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=742-2289&viewport=301%2C2975%2C0.66&scaling=min-zoom)
[UI feedback working doc](https://docs.google.com/document/d/14WTXtiNGYG3Y7CRkhrD_tdKELZ3coEuyyJ0iXT6Eamw/edit?usp=sharing)

@mdshamoon

**Comment by nairabhishek73** [comment]
Change schedule is not working.

**Comment by nairabhishek73** [comment]
https://ddpstagingui.projecttech4dev.org/pipeline/orchestrate
ii. Schedule is still written twice when adding new flow
iii. I edited and changed to weekly and it says sucesffully changed. But back on the main orchestrate screen it still says daily. (check video)

https://github.com/DevDataPlatform/webapp/assets/119285990/d26a8198-9290-4222-bb71-e7ed4e4122ca

**Comment by Ishankoradia** [comment]
@nairabhishek73 the word `daily` is the name of the flow entered by user. It can be anything and has nothing to do with the schedule of the flow

**Comment by nairabhishek73** [comment]
Ah alright. Only "ii. Schedule is still written twice when adding new flow" this then

**Comment by fatchat** [comment]
@Ishankoradia would you please change the label to "daily / weekly"
