### ISSUE TITLE
6. Cleanup the entire DDP UI design elements to match Figma

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#109]
**Describe the task**
All formatting should match that of Figma. With icons font characteristics, colour palette, box sizes etc.

**References**
[DDP UI](https://ddpui.projecttech4dev.org/pipeline) 
[Figma](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=742-2289&viewport=301%2C2975%2C0.66&scaling=min-zoom)
[UI feedback working doc](https://docs.google.com/document/d/14WTXtiNGYG3Y7CRkhrD_tdKELZ3coEuyyJ0iXT6Eamw/edit?usp=sharing)

@mdshamoon

**Comment by nairabhishek73** [comment]
Fonts don't seem to be matching across all pages. Noticed in Login, overview, ingest, orchestrate. Please check font type, size, bold/not.

**Comment by fatchat** [comment]
Linked to C4GT Community issue https://github.com/DevDataPlatform/webapp/issues/163
