### ISSUE TITLE
9. update the signup page on the DDP UI

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#112]
**Describe the task**
1. Follow the design
2. Validate email ID
3. Validate password
4. Add option to see password

**Expected behaviour**
All formatting should match that of Figma. With icons font characteristica, colour palette, etc.
All changes should be made as listed above.

**References**
[DDP UI](https://ddpui.projecttech4dev.org/pipeline) 
[Figma](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=863-12111&viewport=301%2C2975%2C0.66&scaling=min-zoom)
[UI feedback working doc](https://docs.google.com/document/d/14WTXtiNGYG3Y7CRkhrD_tdKELZ3coEuyyJ0iXT6Eamw/edit?usp=sharing)

@mdshamoon

**Comment by nairabhishek73** [comment]
Points 2,3,4 pending

**Comment by fatchat** [comment]
Linked to C4GT Community issue https://github.com/DevDataPlatform/webapp/issues/165
