### ISSUE TITLE
10. Update the Login page on the DDP UI

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#113]
**Describe the task**
1. Login box to be made bigger
2. Add Forgot password option missing
3. Should default to sign in. With signup up at the bottom
4. Font colours are different on home page

**Expected behaviour**
All formatting should match that of Figma. With icons font characteristica, colour palette, etc.
All changes should be made as listed above.

**References**
[DDP UI](https://ddpui.projecttech4dev.org/signup) 
[Figma](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=1031-235&viewport=301%2C2975%2C0.66&scaling=min-zoom)
[UI feedback working doc](https://docs.google.com/document/d/14WTXtiNGYG3Y7CRkhrD_tdKELZ3coEuyyJ0iXT6Eamw/edit?usp=sharing)

@mdshamoon

**Comment by nairabhishek73** [comment]
Forget password option is different from Figma

**Comment by fatchat** [comment]
Linked remaining two tasks with the C4GT Community issue https://github.com/DevDataPlatform/webapp/issues/164
