### ISSUE TITLE
Figma alignment: Fonts / C4GT

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#163]
### Description
We are aligning our application with our Figma design

### Goals

Align fonts, sizes and styles with [the design](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=742-2289&viewport=301%2C2975%2C0.66&scaling=min-zoom)

### Project Name
DevDataPlatform

### Organization Name
Project Tech4Dev

### Domain
Social Sector

### Complexity
Easy

### Tech Skills Needed
NextJS

### Mentor(s)
@fatchat 

### Category
Enhancement

### Sub Category
UI

### Product Set-Up

https://github.com/DevDataPlatform/webapp/blob/main/README.md

You will need the following `.env`

`NEXT_PUBLIC_BACKEND_URL="https://ddpapi.projecttech4dev.org"`

`NEXTAUTH_SECRET=<generate-your-own-secret-using-https://generate-secret.vercel.app/32>`

`NEXTAUTH_URL="http://localhost:3000"`

You will also require a "signup code" which we will provide. Please reach out to us when you are ready for this

### Acceptance Criteria
PR merged into the main branch

**Comment by fatchat** [comment]
Step 1: Signup. Login, Forgot & Reset password
Step 2: Overview, Orchestrate
Step 3: Transform
Step 4: Ingest: Sources
Step 5: Ingest: Destinations
Step 6: Ingest: Connections

Every word should match the Figma design: font family, font size, font style (bold, italic)

**Comment by jayanth-kumar-morem** [comment]
### Pages up for cross verification with Figma design

- [ ] Signup
- [ ] OTP Verification
- [ ] Who you are 
- [ ] send invite 
- [ ] invite
- [ ] invited user sign up
- [ ] create org
- [ ] add warehouse
- [ ] add source
- [ ] add more source
- [ ] Tranformation
- [ ] Login
- [ ] Forgot & Reset password
- [ ] Dashboard
- [ ] Data pipeline
- [ ] connections
- [ ] view logs
- [ ] new/edit/delete connection
- [ ] add/edit/delete source
- [ ] warehouse
- [ ] flows (active)
- [ ] flow log view
- [ ] sequence
- [ ] delete flow
- [ ] flow
- [ ] create flow
- [ ] edit flow details
- [ ] settings
- [ ] logout
- [ ] Add user
- [ ] Edit details
- [ ] Toast messages
- [ ] connections sync
