### ISSUE TITLE
serve dbt docs

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#174]
after setting up the dbt workspace and running `dbt docs`, show the docs in an iframe

**Comment by fatchat** [comment]
tabbed container under page title "Transformation"

Tab 1 is called "Connect" until workspace is set up, then name changes to "Run"
Tab 2 is called "Documentation"

Tab 1 remains as-is including the "dbt run" in the dropdown

Tab 2 only embeds the iframe and has no UX

**Comment by nairabhishek73** [comment]
Looks good overall
1) I could only see ddp docs for stir, sneha and shri weren't showing up- saying not generated
2) When a workspace is not setup there's a add option and the edit option is still active- both direct to connect a new transformation. Ideally edit is inactive when you haven't added in any transformation (low priority change)

**Comment by fatchat** [comment]
"not generated" => have to run "docs generate" from the first tab. I'll put in a message to that effect
will disable / remove edit when there isn't anything to

**Comment by fatchat** [comment]
closing since we decide to hide via #229
