### ISSUE TITLE
commcare connector not checking credentials during setup

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#197]

**Comment by fatchat** [comment]
deployed to staging and verified: bad credentials are blocked during source creation & edit, good credentials still go through

**Comment by nairabhishek73** [comment]
This is working. Once I got an odd error saying to match the date format. Though I didn't touch the date at all and cannot replicate.

**Comment by fatchat** [comment]
we will ask @siddhant3030 to

- put the date format into the help strings for all date fields for all our connectors; update `connectionSpecification.properties.<date_field>.title` 
- mark all fields which are required as required

Siddhant please open the relevant issues and add them to the DDP project for the next sprint

Closing this issue now @nairabhishek73
