### ISSUE TITLE
form should update when changing value of dropdown

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#198]
**Describe the bug**

**To Reproduce**
1. Go to "Sources" -> "Add Source"
2. Select Google Sheets
3. Select "Client" as the "Authentication" type
4. New fields will appear
5. Change "Client" to "Service"
6. The fields for "Service" will not appear... instead the Client fields disappear

**Expected behavior**
When switching between Client and Service, the form should update and show the relevant fields

**Comment by fatchat** [comment]
when alt-tabbing away from the window and back,  the dynamic fields disappear

**Comment by nairabhishek73** [comment]
Discussed with Ishan. Can we only mark something as closed once its been pushed to staging and tested and then is on production as well.
