### ISSUE TITLE
figure out superset login via ajax

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#199]
If we embed superset in an iframe within our webapp, we will want a uniform login experience. to this end, if the webapp has superset's login credentials we should be able to pass them to the iframe and login

step 1: find the structure of the login request from superset in the browser to the flask backend

**Comment by Abhishek-N** [comment]
**Login Function**

**1. Get Access Token**

- Endpoint: POST `http://localhost/api/v1/security/login`
- Request: The function sends a JSON payload containing the `username`, `password`, and `provider` (authentication method).
`{
  "username": "username",
  "password": "password",
  "provider": "db"
}`
- Response: It receives a JSON object with an access_token
`{
    "access_token": "*****"
}`

**2. Fetch CSRF Token**

- Endpoint: GET `http://localhost/api/v1/security/csrf_token/`
- Request: The function includes the access_token in the Authorization header as a bearer token.
`headers: {
    'Authorization': Bearer ${accessToken}
  }`
- Response: The server provides a JSON object containing the `csrf_token`
`{
    "result": "****"
}`

**3. Login Request**

- Endpoint: `POST http://localhost/login/`
- Request: The function sends a POST request with user credentials encoded in the request body and includes the `csrf_token` in the `X-CSRFToken` header for security
`{
  "username": "username",
  "password": "password"
}`
- Response: The server responds with a status indicating successful login or failure.

**Comment by Abhishek-N** [comment]
Blog on the same: [https://projecttech4dev.org/2023/08/01/achieving-seamless-superset-login-for-embedded-iframes/](url)
