### ISSUE TITLE
User invitations

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#213]
Admins can invite other Admins

(Note that the only users for the django application are admins now)

"User Mgmt" page with tabs:
- [Tab 1] list view of all users (including account owner)
- [Tab 2] list view of open invitations

"invite user" above the tabs opens a dialog with a single field: email address
response: "user having this email already exists" or "invitation sent to <email address> from <sender-email>" 

list of users: email address & role. account owner gets a button "delete user" which deletes after confirmation

list of open invitations: email address and two actions, "resend email" and "revoke invitation"

**Comment by fatchat** [comment]
"deleting a user" means deleting the OrgUser - don't touch the User

**Comment by fatchat** [comment]
@nairabhishek73 ready for review

https://ddpstagingui.projecttech4dev.org/

**Comment by nairabhishek73** [comment]
1. Can the invitation say who has invited you? ex: abhishek.nair@projecttech4dev is inviting you to join DDP as a pipeline manager
2. We need to show what actions the role can and cannot take.
3. Ideally pipeline manager cannot invite users right? Currently they can
4. I can invite the same email ID twice. That user can setup their password and then when I’m asked to sign in neither my old nor new password work.
4a.When inviting the same email ID it should not allow me and notify me on the UI that this user already exists.
5. Error popping up if I click on an old invite or if I am already logged in. Not sure which. Ref Screenshot
6. As the admin, it seems i can delete myself as a user. When I do this it says organisation deleted. But i remain on the DDP UI page. 
6a. If I delete myself it should inform me of what it going to happen. Ideally I am logged out and the organisation is deleted if there is no other user. If there is another user it should ask me if i want to transfer ownership.
6b. Following deletion I can no longer login, nor can I signup again.

@fatchat

**Comment by fatchat** [comment]
1. yes we can add that to the email
2. right now they can do everything, so listing the actions would be an entire tutorial
3. yes, in future user-mgmt and pipeline-mgmt will be separated e.g. for third-party consultants
4. right now inviting the same user again results in resending the email - you shouldn't see a new entry in the "pending invites" list. we could change that but the end state is the same. if the user already has a dalgo account then they should not be asked for a new password - ishan is making that change right now. in the logic currently released the new password is ignored so your old one should work... please try from another browser because this may be related to the other bug we're fixing
5. cannot reproduce, i hope it is related to the other bug
6. you should not be able to delete yourself, ishan is making that change. there are too many downstream effects, the correct flow is for another user to delete you. if you're an account owner, then first ownership needs to be transferred and then the new owner deletes you. not planned for this sprint... but we could do it if you think it important 

6b. oh right... we'll fix this today as well

**Comment by nairabhishek73** [comment]
4. I was able to see the new entry in pending invites. 
5. Alright.
6. Lets do it in this sprint if we wrap everything else up. Else push to next sprint.

**Comment by fatchat** [comment]
4. you are correct - we guard against duplicate open invitations to the same user but not against issuing an invitation to an existing user (!!) this will be fixed
6. has been done - i.e. you can't delete yourself nor can you delete an account manager... although for the latter the UX allows you to try before you fail
7. #259

**Comment by nairabhishek73** [comment]
5. Could we eliminate the option for this and for a pipeline manager making another pipeline manager account manager. Not urgent, but in the next 2 sprints.

**Comment by fatchat** [comment]
4. fixed via https://github.com/DevDataPlatform/DDP_backend/pull/266
5. #265

**Comment by fatchat** [comment]
github is automatically renumbering our list items... no. 6 three comments above is actually no. 7
