### ISSUE TITLE
Survey CTO 'add source' should ask for "Form ID/s" not "Form's Id"

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#219]

**Comment by fatchat** [comment]
@siddhant3030 @avirajsingh7 `airbyte-integrations/connectors/source-surveycto/source_surveycto/spec.yaml`

**Comment by avirajsingh7** [comment]
changed and merged in airbyte main repo

**Comment by fatchat** [comment]
yes it is! but we have not upgraded airbyte on our platform yet... so i am re-opening this until then

**Comment by fatchat** [comment]
pull those changes into our local copy of the connector @fatchat

**Comment by fatchat** [comment]
![Image](https://github.com/DevDataPlatform/webapp/assets/2160416/eba9a8c8-cc82-44ac-ba36-a9eae5f7b636)
