### ISSUE TITLE
DBT page: Select action and then run it

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#238]
The current behaviour is that the "Run" button executes `dbt run` and selection from the dropdown executes that action

Make this a consistent two-step: 
1. Select the action to the executed (dropdown)
2. Execute it (run button)

**Comment by fatchat** [comment]
@nairabhishek73 ready for review

**Comment by nairabhishek73** [comment]
1. the box to the right of the word execute should be a fixed size, currently when blank its a small square with an arrow, it should read "select function"
2. Also the select function box should come first and the execute option should be to its right. So you select the function, then you execute.

<img width="1163" alt="Screenshot 2023-08-04 at 6 30 47 PM" src="https://github.com/DevDataPlatform/webapp/assets/119285990/664a7949-cb7e-409e-b118-0277f86e4edc">

**Comment by fatchat** [comment]
2. the actions are listed in the order in which they "should" be run. the user is free to run them in any order (or even run just one of them) but the listed order is the recommended one

other points covered by PR #263

**Comment by nairabhishek73** [comment]
Alright!
