### ISSUE TITLE
Select Org if user has multiple

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#239]
When a user is part of multiple organizations, allow them to switch between them

need a UI @nairabhishek73  ... when the list is small we can put it into the profile drop-down in the top-right corner of the page

But as the list grows (more than 10?) that will become unwieldy... we could solve this now or after people are attached to more than 10 orgs i.e. after a few months

**Comment by fatchat** [comment]
@nairabhishek73 for your review

**Comment by nairabhishek73** [comment]
This seems to be working fine. We can solve for the +10 orgs problem when it comes up. For now can we make the current org in the top right Drop Down bold. The subtle highlight is not a great indication.

**Comment by fatchat** [comment]
@nairabhishek73 bold styling added
