### ISSUE TITLE
Embedded Superset

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#240]
Fetch from `/currentuser` :
- the superset url 
- the superset login type (username + password / google oauth / [other oauth in future])

If the client is not paying for Superset, these responses will be empty. But in case they are not, then:

Display Superset in a new "Analytics" page
- <iframe src = superset url>

And for unified login:
- if login type is u+p, send u+p to the iframe for the login action
- if login type is google oauth, send a message to the iframe to click the button

The iframe will contain a JavaScript listener which will
- listen for the login message
- execute the login flow from https://github.com/DevDataPlatform/webapp/issues/199 if username+password login
- find the login button and click it if Google OAuth login

Error reporting
- None, if the login fails the user will see it on their screen
- And anyway there's nothing we can do short of showing a redundant "login failed" message above the iframe

**Comment by vinod-rajasekaran** [comment]
Fetch from /currentuser :

the superset url
the superset login type (username + password / google oauth / [other oauth in future])

**This will be from org API endpoint of current user in future - 0.2/0.3 ?**

If the client is not paying for Superset, these responses will be empty. But in case they are not, then:

Display Superset in a new "Analytics" page

** If superset is not enabled for org, page should display with message " Superset not Enabled - Call to action button to contact Sales to enable or something like this **


<iframe src = superset url>
And for unified login:

if login type is u+p, send u+p to the iframe for the login action
if login type is google oauth, send a message to the iframe to click the button
The iframe will contain a JavaScript listener which will

**How will we know username and password for user in superset ? **
**If superset is on OAuth, will user need to login now into Google as we are only doing user+password on DDP ? **

listen for the login message
execute the login flow from https://github.com/DevDataPlatform/webapp/issues/199 if username+password login
find the login button and click it if Google OAuth login
Error reporting

None, if the login fails the user will see it on their screen
And anyway there's nothing we can do short of showing a redundant "login failed" message above the iframe

**Comment by fatchat** [comment]
we were not able to implement google oauth login inside the iframe

so for oauth logins
- login in a new window and come back to the iframe

for u+p logins
- they can log in inside the iframe - no automatic login at this time, we can do it in a future release

**Comment by Ishankoradia** [comment]
superset is embedded. 

1) for oauth logins users will have to type their u + p and login in to the embed superset.

2) for google oauth, we will have a `google siginin` button on the top/besides the iframe. Users will have to login via the button since oauth doesn't work in iframes. We tried to close the popup window of oauth by using messge and event listeners, however it is not possible to fetch the location of the child window once the user is logged in. 


Parent (webapp)
```
var locationStatusInterval = setInterval(() => {
      authWindow?.postMessage(
        { ask: 'locationStatus' },
        `${globalContext?.CurrentOrg?.state.viz_url}/#child`
      );
    }, 2000);

window?.addEventListener('message', (event) => {
      console.log('receieved something', event.data);
      const message = event.data;
      if (
        message?.locationStatus &&
        message.locationStatus === '/superset/welcome/'
      ) {
        console.log('asking the window to be closed', message.locationStatus);
        authWindow?.close();
        authWindow = null;
        clearInterval(locationStatusInterval);
      }
    });
```

Child popup (for google oauth)
Code for this is in one of the html files of superset.
```
console.log("base layout loaded");
window.addEventListener("message", function (event) {
        const message = event.data;
        console.log("someone asked for soemthign");
        if (message?.ask === "locationStatus") {
            console.log("someone asked for locationStatus");
            event.source.postMessage({ locationStatus: window.location.pathname }, event.origin);
        }
    });
```

**Comment by nairabhishek73** [comment]
Problems:

1. Don't show the I frame if the user isn't logged in (if the I frame is shown then the natural next step for the user will be to click on sign in with google)
2. One I login through the popup window the i frame needs to reload and show me superset immediately. (currently no change in. the page till i move to another opage and come back)
3. If they login sucessfully, then make the log in button at the top right disappear.
4. If they log out it should go back to point 1.

**Comment by fatchat** [comment]
@nairabhishek73

**Comment by nairabhishek73** [comment]
1. Its taking a noticeable 3 seconds for the "Google Sign in" (also note there should be a space between Sign and in) option to pop up everytime I go to the Analysis tab. Enough time for me to panic and click elsewhere.
This delay applies even to embedded superset after i've logged in.
2. Its loading immediately on our UI once i sign in on the pop up window. That's great.
3. I am not required to login to superset again if I logout from DDP UI and then log back in. This is great.

We could choose to address point 1 now or later(as a separate issue).

**Comment by fatchat** [comment]
Let’s put in a loading indicator

During these three seconds there’s nothing else in the panel right, other
than the word “Analysis”?

**Comment by fatchat** [comment]
ok done @nairabhishek73

**Comment by nairabhishek73** [comment]
Works. Loading symbol was a great idea.
