### ISSUE TITLE
Last Sync Date does not seem to be accurate

### ISSUE THREAD

**Issue by vinod-rajasekaran** [DevDataPlatform/webapp#249]
**Describe the bug**
Checked on SNEHA DB - last sync was on July 26 but last sync seems as 13 days ago which is not matching as of today's date - unsure if this is pulling the first date

<img width="1177" alt="Screenshot 2023-08-03 at 12 08 40 PM" src="https://github.com/DevDataPlatform/webapp/assets/23266611/0cd497c7-f0c9-4e52-83fa-bf3f5f24e6d0">
<img width="1470" alt="Screenshot 2023-08-03 at 12 15 35 PM" src="https://github.com/DevDataPlatform/webapp/assets/23266611/05ae1473-14e5-44c6-9cdc-b3567c0406a3">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fatchat** [comment]
the "connections" screen shows the date of the last manual sync not the last regularly scheduled sync

this was intentional; we can change it @nairabhishek73

**Comment by vinod-rajasekaran** [comment]
I would prefer any sync done for that air byte connection - the casual user will get confused with the current sync status in my opinion

**Comment by nairabhishek73** [comment]
Agreed with @vinod-rajasekaran . Also we should show tags for manual or scheduled.

**Comment by nairabhishek73** [comment]
In Orchestrate make it "Last Scheduled Run"
In Ingest make it "Last Manual Sync"

**Comment by fatchat** [comment]
this is a short-term fix to avoid confusion, after v1 we can show the last sync date of the connection #307

**Comment by fatchat** [comment]
@nairabhishek73 for your review

**Comment by nairabhishek73** [comment]
Works
