### ISSUE TITLE
On flow deletion, issue stays on screen until page is refreshed

### ISSUE THREAD

**Issue by vinod-rajasekaran** [DevDataPlatform/webapp#250]
**Describe the bug**
On flow deletion, issue stays on screen until page is refreshed

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fatchat** [comment]
@jayanth-kumar-morem this is similar to #215 

https://ddp-prod-ui.projecttech4dev.org/pipeline/orchestrate

**Comment by fatchat** [comment]
this seems to be working, tested on production as well
