### ISSUE TITLE
Preselect streams and sync mode as incremental by default

### ISSUE THREAD

**Issue by vinod-rajasekaran** [DevDataPlatform/webapp#251]
**Is your feature request related to a problem? Please describe.**
Preselect streams and sync mode as incremental by default
Frustrating to select 100 streams for sneha and select incremental while doing a connection
<img width="1470" alt="Screenshot 2023-08-03 at 12 48 14 PM" src="https://github.com/DevDataPlatform/webapp/assets/23266611/f02cff48-68ab-4ff2-8c77-0a3995f7286c">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fatchat** [comment]
#258

**Comment by fatchat** [comment]
now we have toggle-all for sync and for incremental, so not settings defaults

**Comment by nairabhishek73** [comment]
Works
