### ISSUE TITLE
Issue when sync is pressed with existing sync

### ISSUE THREAD

**Issue by vinod-rajasekaran** [DevDataPlatform/webapp#252]
**Describe the bug**
On syncing a connection, it is unclear whether the sync is working as prefect message of "waiting for airbyte shows with no progress in logs". If user refreshes sync button gets active and on pressing the logs start and then bomb out later with below error:

Logs

- Downloading flow code from storage at '/home/ddp/prefect-proxy' ' '
- Created subflow run 'massive-coua' for flow 'run-connection-sync' ' '
- Created task run 'trigger-0' for task 'trigger' ' '
- Executing 'trigger-0' immediately... ' '
- Triggering Airbyte Connection 205bca73-3144-499d-9c4c-fda0e38e182d, in workspace at 'http://localhost:8000/api/v1' ' '
- Encountered exception during execution: Traceback (most recent call last): File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/client.py", line 154, in trigger_manual_sync_connection response.raise_for_status() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status raise HTTPStatusError(message, request=request, response=self) httpx.HTTPStatusError: Client error '409 Conflict' for url 'http://localhost:8000/api/v1/connections/sync/' For more information check: https://httpstatuses.com/409 The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/engine.py", line 1719, in orchestrate_task_run result = await call.aresult() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult return await asyncio.wrap_future(self.future) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async result = await coro File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/connections.py", line 367, in trigger (job_id, _,) = await airbyte_client.trigger_manual_sync_connection( File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/client.py", line 166, in trigger_manual_sync_connection raise err.AirbyteServerNotHealthyException() from e prefect_airbyte.exceptions.AirbyteServerNotHealthyException ' '
- Finished in state Failed('Task run encountered an exception AirbyteServerNotHealthyException: ') ' '
- Encountered exception during execution: Traceback (most recent call last): File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/client.py", line 154, in trigger_manual_sync_connection response.raise_for_status() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status raise HTTPStatusError(message, request=request, response=self) httpx.HTTPStatusError: Client error '409 Conflict' for url 'http://localhost:8000/api/v1/connections/sync/' For more information check: https://httpstatuses.com/409 The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/engine.py", line 833, in orchestrate_flow_run result = await flow_call.aresult() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult return await asyncio.wrap_future(self.future) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async result = await coro File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/flows.py", line 57, in run_connection_sync airbyte_sync = await task(airbyte_connection.trigger.aio)(airbyte_connection) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 182, in wait_for_call_in_loop_thread return call.result() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result return self.future.result(timeout=timeout) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result return self.__get_result() File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result raise self._exception File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async result = await coro File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/engine.py", line 1302, in get_task_call_return_value return await future._result() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/futures.py", line 237, in _result return await final_state.result(raise_on_failure=raise_on_failure, fetch=True) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result raise await get_state_exception(state) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/engine.py", line 1719, in orchestrate_task_run result = await call.aresult() File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult return await asyncio.wrap_future(self.future) File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async result = await coro File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/connections.py", line 367, in trigger (job_id, _,) = await airbyte_client.trigger_manual_sync_connection( File "/home/ddp/prefect/venv/lib/python3.10/site-packages/prefect_airbyte/client.py", line 166, in trigger_manual_sync_connection raise err.AirbyteServerNotHealthyException() from e prefect_airbyte.exceptions.AirbyteServerNotHealthyException ' '
- Finished in state Failed('Flow run encountered an exception. AirbyteServerNotHealthyException: ') ' '
- Finished in state Failed('1/1 states failed.') ' '
- 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fatchat** [comment]
this should also be covered by #255
