### ISSUE TITLE
Connections-Commcare- toggle all

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#258]
**Is your feature request related to a problem? Please describe.**
I I need to connect to multiple forms for commcare I need to toggle each and every form individually for sync and incremental. Thats more than 60 clicks

**Describe the solution you'd like**

1. A select all option.
2. A search option
3. Vinod mentioned we should just copy how airbyte does it. 

**Describe alternatives you've considered**
None

**Additional context**

![Image](https://github.com/DevDataPlatform/webapp/assets/119285990/6ef92438-a563-48f0-8f4c-0edb620dca6f)

**Comment by fatchat** [comment]
what is 
2. a search option

what do you want to search for

**Comment by nairabhishek73** [comment]
Want to search for the relevant streams.

**Comment by fatchat** [comment]
#251 asked that all streams be selected by default, as incremental where possible

**Comment by nairabhishek73** [comment]
Works
