### ISSUE TITLE
Signup email verification process

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#259]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 
When a new user signs up they are able to access the UI immediately. At the sae time an email goes out to the user asking for verification of emailID.

**Describe the solution you'd like**
When the first user signs up the screen should display 
"Congratulations for signing up on Dalgo! Kindly check your inbox @ *email id* and click on the link to complete your signup process"
"if you have signed up with and incorrect email address __click here__"

**Comment by fatchat** [comment]
add a "logout" button under the "send verification email" button

**Comment by fatchat** [comment]
@nairabhishek73
