### ISSUE TITLE
Website creation

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#275]
@Ishankoradia @fatchat who will do this? Think 201 will give us the design's first cut by the 18th.

**Comment by fatchat** [comment]
Prod showed us a version yesterday, feedback was given and another meeting will happen today

**Comment by nairabhishek73** [comment]
Complete at dalgo.in
Please share feedback on: https://docs.google.com/document/d/12RueYQtokXXPnhJnVZXOXMM7Kip8IyInl8S2js072ME/edit?usp=sharing
