### ISSUE TITLE
unable to create new surveycto source

### ISSUE THREAD

**Issue by jakejh** [DevDataPlatform/webapp#290]
When I enter all the info in the "add a new source" window and then click "Save changes and test", nothing happens.

Also, the ordering of source types in the dropdown seems weird, it's not alphabetical.

**Comment by fatchat** [comment]
@siddhant3030 is "Form IDs" a required field? 

@jakejh In case it is, our UI has the charming feature that after you type in the form id you have to hit <Enter>

**Comment by siddhant3030** [comment]
@jakejh yes. form id's are required field.

**Comment by jakejh** [comment]
Oh, I see what you mean. Yeah, that's confusing.

Ok, I got the connection set up, but the UI did this weird thing where the first time I hit "connect" it said "failed ...", then I tried again and it eventually worked, and now it seems to have duplicated the connection.

Then when I hit sync the first time, a red message came up that said "deployment not created", but the sync is running.

**Comment by jakejh** [comment]
But apparently the sync didn't actually run, because it still says last sync "not available" and there's nothing in bigquery.

**Comment by siddhant3030** [comment]
@jakejh do you want to quicky and I can take a look maybe? Can share the link on discord

**Comment by siddhant3030** [comment]
@jakejh I'm closing this issue since you resolved this yesterday and you're able to see the normalized data. Also incremental was working for you
