### ISSUE TITLE
if user has no orgs, send them to an org-creation page

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#297]

**Comment by fatchat** [comment]
once their email address has been verified

**Comment by nairabhishek73** [comment]
Takes me to welcome, please contact dalgo to setup your account. If tech4dev/goalkeep/TAF/ other partner then give org.
If trial user, then give staging org. 
What would the step after this look like on the UI?

**Comment by fatchat** [comment]
staging org is a good idea, needs to be thought through 

i'd suggest we provide a warehouse and a single data source, let them experience setting up the connection

transformation... we provide a dbt repo which works on that single data source

orchestration ... let them set up a pipeline and run it. no scheduling

every night we wipe the test orgs, delete their logins etc

**Comment by nairabhishek73** [comment]
We had discussed 1 month trials right? Once a month sign in code changes and clearing.  
I think we should allow a full trial, which would include scheduling and superset too. Won't bee too many folks availing.
Do we need to do the DBT repo setup?

**Comment by fatchat** [comment]
My impression of that conversation was that this is something we would like to do in future

It is not on the dev roadmap right now, but we can talk about putting it on

Go ahead and spec it out, I'll tell you how quickly we can implement it

**Comment by nairabhishek73** [comment]
Works thanks!
