### ISSUE TITLE
Setting up the http client

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#3]
I'm assuming that when we make requests to the backend we will do so via some uniform mechanism, could that be defined please

This should 
- automatically select the API endpoint based on dev/prod
- include the user's `Bearer token` in the http headers
- check each response for `response.error`, and if it exists then `console.error` it before returning to the caller

The users `Bearer token` will need to be defined in some store along with its getter and setter

**Comment by mdshamoon** [comment]
We will be using [SWR](https://swr.vercel.app/docs/getting-started) as this is the recommended way in a nextjs application for making requests to the backend. For storing the token we will use localstorage.

Things to be done-

- Create a getter and setter for the token that will be stored in the browsers localstorage.
- Create an env file with the configuration for the backend URL
- Add global configuration for SWR in _app.tsx that 
   - Sends the authentication header along with each request.
   - Print error on console before returning to the user. Eventually we will add logs here.

**Comment by fatchat** [comment]
sorry, but "store" i meant something like redux, will we use anything like that?

SWR looks very nice, does it do POST as well? i only saw fetch() when i glanced through their documentation...

**Comment by mdshamoon** [comment]
We will most probably use the react context api if the need arises. I don't think we would need a full-fledged state management library here. 

fetch is the latest JS API to make external calls. It supports all the HTTP request methods.
