### ISSUE TITLE
orchestration settings should show display name

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#304]
show name instead of deploymentName

<img width="538" alt="image" src="https://github.com/DevDataPlatform/webapp/assets/2160416/e28769c4-9d0a-467e-8482-a6e8d0869740">

**Comment by fatchat** [comment]
also in the orchestration list view, we've set the "last run status" to "running" perhaps we should change it to "succeeded" @nairabhishek73 

<img width="106" alt="image" src="https://github.com/DevDataPlatform/webapp/assets/2160416/6f734eeb-6911-4cea-bbfc-0682ffda192f">

**Comment by fatchat** [comment]
@nairabhishek73 for your review

**Comment by nairabhishek73** [comment]
Could we just make it "Success"

**Comment by fatchat** [comment]
@nairabhishek73 done

**Comment by nairabhishek73** [comment]
works
