### ISSUE TITLE
N1-Remove the word "Last Run" from the orchestrate information since its already there in the column name.

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#315]

**Comment by nairabhishek73** [comment]
![Image](https://github.com/DevDataPlatform/webapp/assets/119285990/579fe35f-3314-4a83-83d1-f35613a2868d)

In this case it should just say not available

**Comment by fatchat** [comment]
show the time of the last run - successful or failed

**Comment by fatchat** [comment]
and if there is no last run let's just put a dash  (&mdash;)

**Comment by Ishankoradia** [comment]
This is basically a frontend issue, backend we are fetching last run based on both success or failed. But however in failed runs sometimes `startTime` is null so we need to use the `expectedStartTime` to show the last run

**Comment by fatchat** [comment]
@nairabhishek73  ready for review

**Comment by nairabhishek73** [comment]
Works
