### ISSUE TITLE
N2.Sneha embedded superset is taking too long to load- over 20 seconds and no result

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#316]

**Comment by siddhant3030** [comment]
I can't even see the loading.

**Comment by siddhant3030** [comment]
![Uploading Screenshot 2023-08-22 at 9.07.40 AM.png…]()

**Comment by siddhant3030** [comment]
<img width="1433" alt="Screenshot 2023-08-22 at 9 07 40 AM" src="https://github.com/DevDataPlatform/webapp/assets/9019958/a67074ca-fb92-4dca-85bb-c9af9c2280a7">

**Comment by fatchat** [comment]
site is down

**Comment by fatchat** [comment]
rebooted the `esuper` machine, superset is back up

i'll build a new machine for your guys, closing this issue
