### ISSUE TITLE
N3: when I sign up for the first time its saying "sucessfully logged in" and then taking me to the "send email verification screen"

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#322]

**Comment by fatchat** [comment]
this is the intended behavior - after account creation the user cannot proceed until they verify their email address

but yes we can make it less confusing / jarring

suggestions are welcome

**Comment by fatchat** [comment]
remove the success toast

**Comment by fatchat** [comment]
there is no success toast
