### ISSUE TITLE
Creation of new org should switch to new org

### ISSUE THREAD

**Issue by nairabhishek73** [DevDataPlatform/webapp#339]
https://jam.dev/c/dcfda36c-4e63-4ee7-8fa0-5ace72665c57

**Comment by fatchat** [comment]
@Ishankoradia can you update the slug in ls upon new org creation

**Comment by nairabhishek73** [comment]
Important to do before release to users.

**Comment by nairabhishek73** [comment]
Seems my ID doesn't have permission to create a new org onn staging

**Comment by Ishankoradia** [comment]
which are you using ? Let me know, will give the permission.

**Comment by nairabhishek73** [comment]
Thanks Ishan! This works
