### ISSUE TITLE
Issues with destination name and connection

### ISSUE THREAD

**Issue by Abhishek-N** [DevDataPlatform/webapp#55]
1. When creating a destination with its name, it is not saved as entered. Instead, it shows ‘postgres-warehouse’ after it is saved.

2. While creating a connection, we can only add the destination schema but not the destination we want to connect to.

**Comment by fatchat** [comment]
1. Is a bug
2. Is by design - only one warehouse. The UX is confusing though…

**Comment by fatchat** [comment]
Schema for bigquery is called a “dataset”, we should update our UI

**Comment by Abhishek-N** [comment]
> 

can we not add more than one postgres destination?
