### ISSUE TITLE
Create structure for the multi step form

### ISSUE THREAD

**Issue by mdshamoon** [DevDataPlatform/webapp#6]
**Describe the task**
While onboarding a new organization the user has to fill up an onboarding form which takes the details in a multi step process.
Refer the [design](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=1031-559&viewport=301%2C2975%2C0.66&scaling=min-zoom) prototypes for the process. 

For this we will need to create a multi step form structure on the left where each step is denoted by a highlighted circle and the status section on the right.

Pointers to keep in mind while putting up the structure:

- The circles at the left are clickable and we can go back a step by clicking on them.

**Comment by fatchat** [comment]
Removed this from the UX flow
