### ISSUE TITLE
Dbt run doesn't perform the operation immediately

### ISSUE THREAD

**Issue by Abhishek-N** [DevDataPlatform/webapp#68]
1. The buttons are supposed to show `dbt run`, `dbt docs`, `dbt test`. Instead it shows this
<img width="766" alt="Screenshot 2023-06-01 at 4 31 05 PM" src="https://github.com/DevDataPlatform/webapp/assets/35729337/0b061c8b-487c-44da-99ac-8fe8ec4982f7">

2. `dbt run` - DBT doesn't run the sync immediately and it shows popup `Job run successfully`. Transformation only happens after scheduling.

**Comment by fatchat** [comment]
1. Yes this is a temporary UI, its not supposed to look like this
2. DBT does not sync data... the button for "dbt run" is only supposed to run the dbt job. And it should (please see `transform.tsx:runDbtJob`), did you run it and not see the Prefect flow-run?

**Comment by fatchat** [comment]
with the new buttons, now the job(s) run immediately
