### ISSUE TITLE
Increase code coverage to 50%

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/webapp#77]
**Describe the task**
Our code coverage is currently at 25.75%. Our goal is to get it above 80%. As a first step towards this goal, this issue will get the coverage above 50%

**Expected behavior**
CodeCov will report a coverage of at least 50%

**References**
[CodeCov](https://app.codecov.io/gh/DevDataPlatform)
[Jest](https://jestjs.io/)
[Example test](https://github.com/DevDataPlatform/webapp/blob/main/src/components/SideDrawer/SideDrawer.test.tsx)

**Comment by sanil011** [comment]
can you elaborate the task what should I do to increase the code coverage?

**Comment by sanil011** [comment]
can you elaborate what should i do to increase the code covergage

**Comment by fatchat** [comment]
> can you elaborate what should i do to increase the code covergage

Yes absolutely, have you looked at the three references I added to the initial description

The testing framework is called Jest, you'll need to learn how to use it. I also linked to one of out test files where you will see usage, if you go through the repo you will see other `.test.tsx` files with more example usage

We have not yet started using the full power of Jest, this means that a) we have a lot of work to do!, but also b) what is already there is not too hard to start with

Have a look through things then we can have a meeting. Before the meeting you should have cloned the repo and run "yarn test" once

**Comment by sanil011** [comment]
yeah sure, I will clone the repo and go through the refrences and learn about jest.

**Comment by sanil011** [comment]
local server is not working
<img width="1440" alt="Screenshot 2023-06-06 at 9 19 58 AM" src="https://github.com/DevDataPlatform/webapp/assets/105095685/dff479c7-4a4a-406a-bb56-bc6955edb6d8">

**Comment by fatchat** [comment]
you're not running a local server, that's why. i'm setting up our dev server to accept outside connections, will be done around 2pm i think. will let you know how to connect to it

**Comment by fatchat** [comment]
sorry for the delay, please add this line to your `.env`

`NEXT_PUBLIC_BACKEND_URL="https://ec2-65-2-5-51.ap-south-1.compute.amazonaws.com"`

**Comment by fatchat** [comment]
did you check to see if the application is attempting to connect to localhost or to this amazon machine

**Comment by sanil011** [comment]
I think it is attempting to connect with local host. here is the Screenshot.

<img width="1440" alt="Screenshot 2023-06-06 at 6 29 25 PM" src="https://github.com/DevDataPlatform/webapp/assets/105095685/1b75d88f-35d9-411c-859f-7ebe2d37ae24">

**Comment by fatchat** [comment]
can you show me your full .env?

**Comment by sanil011** [comment]
<img width="1440" alt="Screenshot 2023-06-06 at 10 27 23 PM" src="https://github.com/DevDataPlatform/webapp/assets/105095685/acd610fb-bb11-4622-8813-4a8ce0af056e">

**Comment by fatchat** [comment]
Thanks... btw you can just put the line of text (it's just a few bytes)
instead of pasting a screenshot

Where are NEXTAUTH_SECRET and NEXTAUTH_URL ? You need those too

**Comment by sanil011** [comment]
yes sir, now it is running. sir, can we have a meet?

**Comment by fatchat** [comment]
yes absolutely... just need to fiddle with some DNS settings, can we meet
at 12 noon please? I'll send you a meeting link if you share your email
address

**Comment by sanil011** [comment]
yes, sanilp191@gmail.com

**Comment by fatchat** [comment]
hi @sanil011  good morning, in case you are still working on this please set your `NEXT_PUBLIC_BACKEND_URL` to `https://ddpapi.projecttech4dev.org` in your `.env`

**Comment by sanil011** [comment]
sir, I have read the destination component code. sorry for the late response I am doing an internship also that's why it take time.

**Comment by fatchat** [comment]
No problem, I’m happy you’re interested

I created a branch for this issue so when you start please use that branch
