### ISSUE TITLE
Create signup screen

### ISSUE THREAD

**Issue by mdshamoon** [DevDataPlatform/webapp#8]
**Describe the task**

The login screen will consist 
- Two inputs for email and password.
  - These are required fields and will show an error if we press submit button without entering
- A signup button that redirects to 
  - The **let us know page** if the signup is successful
  - Show an error if its unsuccessful
  - For now we can mock these calls and will connect with the backend later
- A login page link that moves to the login page

**References**
https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=1031-414&viewport=301%2C2975%2C0.66&scaling=min-zoom

**Comment by fatchat** [comment]
don't go to "let us know", go straight to "create organization"
