### ISSUE TITLE
Create a common theme component for all the auth screens

### ISSUE THREAD

**Issue by mdshamoon** [DevDataPlatform/webapp#9]
**Describe the task**
Since all the authentication screen have the same layout we will create a common component for them that will have 

- A left section that contains
  -  A top heading: DDP
  - An area for a form 
  - A footer
- A right section that contains an image

**References**
(https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/DDP-Designs?page-id=702%3A1809&node-id=1031-319&viewport=301%2C2975%2C0.66&scaling=min-zoom)

**Comment by sanil011** [comment]
Hii @mdshamoon, I saw the UI and have a keen interest in the issue. please assign this to me

**Comment by sanil011** [comment]
yes, please

**Comment by fatchat** [comment]
@sanil011 please comment on the issue https://github.com/DevDataPlatform/webapp/issues/77, once you do that I will be able to assign it to you
